valor_hora = float (input("quanto voce ganha por hora? "))
horas_trabalhadas = float(input("quantas horas voce trabalhou no mês? "))
salario_mes = (valor_hora*horas_trabalhadas)
print(f"total do salario no mês: R$ {salario_mes:.2f}")
salario_bruto = salario_mes
print (f"valor do salario bruto: R$ {salario_bruto:.2f}")
IR = (salario_mes*11/100)
print(f"desconto do IR (11%): R$ {IR:.2F}")
INSS = (salario_mes*8/100)
print(f"desconto do INSS (8%): R$ {INSS:.2F}")
sindicato = (salario_mes*5/100)
print(f"desconto do sindicato (5%): R$ {sindicato:.2f}")
salario_liq = (salario_mes-IR-INSS-sindicato)
print(f"valor salario liquido: R$ {salario_liq:.2f}")